### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by mevenson** [Arakula/dasmfw#1]
Following errors when trying to compile:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C3861	'ParseBool':             identifier not found	dasmfw	Dasm6809.cpp	469	
Error	C3861	'SetDefLabelUsed': identifier not found	dasmfw	Dasm6809.cpp	740	
Error	C3861	'SetDefLabelUsed': identifier not found	dasmfw	Dasm6809.cpp	753	
Error	C3861	'SetDefLabelUsed': identifier not found	dasmfw	Dasm6809.cpp	758	
Error	C3861	'SetDefLabelUsed': identifier not found	dasmfw	Dasm6809.cpp	762	
Error	C3861	'SetDefLabelUsed': identifier not found	dasmfw	Dasm6809.cpp	768	
Error	C3861	'SetDefLabelUsed': identifier not found	dasmfw	Dasm6809.cpp	778	
Error	C3861	'SetDefLabelUsed': identifier not found	dasmfw	Dasm6809.cpp	794

**Comment by Arakula** [comment]
Fascinating. Seems I created a little mess back when I last updated this project (17 months ago ... shows the interest :-) ... I'll look into it.

**Comment by Arakula** [comment]
OK, I uploaded a new version that should fix this slightly embarrassing problem.

**Comment by mevenson** [comment]
That fixed it. Thanks
