### ISSUE TITLE
Observation: Character string handling with as65 assembler

### ISSUE THREAD

**Issue by phillipeaton** [Arakula/dasmfw#11]
![image](https://user-images.githubusercontent.com/44277038/172027932-db5fcb14-d856-45e3-ae70-a36d6d937bd5.png)

The above string, when assembled with as65, produces:

![image](https://user-images.githubusercontent.com/44277038/172027997-8486acca-f8d6-4a5e-9a0c-7d906455d9b4.png)

...instead of:

![image](https://user-images.githubusercontent.com/44277038/172027989-90947311-9934-4ffa-9b4c-dd7904c827a0.png)

The backslash would appear to be escaping the '4'. 

The workaround I'm using is (note, binary start address is $2000):

![image](https://user-images.githubusercontent.com/44277038/172028027-c7a5b01b-23e0-49b3-be40-2691e4f0ee94.png)

...which produces:

![image](https://user-images.githubusercontent.com/44277038/172028090-1c4b91c3-f9f9-4bb2-9e6c-38339a316ecd.png)

I'm not sure if a program change is necessary, I suppose you could have a switch to render `\` a non-printing character?

**Comment by Arakula** [comment]
I could, but that's assembler-specific (others might, and do, handle \ as a simple character).
I'll think about it.

**Comment by Arakula** [comment]
And your workaround is a good one.

**Comment by phillipeaton** [comment]
> that's assembler-specific...

So are all the other assembler-specific directives! For example, fcc/fcb seem somewhat obsolete these days 🙂

I'll let you know if I come across any other assemblers that do the same thing.
