### ISSUE TITLE
Unexpected Behaviour: No 'Z' address label being created for 6502 JSR target

### ISSUE THREAD

**Issue by phillipeaton** [Arakula/dasmfw#14]
All of my 6502 JSRs without any `label` show up as below (Z283E)

![image](https://user-images.githubusercontent.com/44277038/179324835-0ce9c541-8ca2-4489-9a3c-69bfab255d00.png)

But later on in my code, I get the following, a `JSR $345C` with a raw address

![image](https://user-images.githubusercontent.com/44277038/179324613-707e705c-bc61-46be-9890-ab8366a2232d.png)

A far as I can see, I don't have any `const` or other directive affecting this JSR or the associated target address. 

I am unable to use `label 345C some_label` to force a label.

The disassembly /reassembly works and I can single step the code without problem.,I just don't understand why it's not creating an automatic label?

Any ideas?

**Comment by phillipeaton** [comment]
I solved this, you may recall I had some `const` workarounds in place for output strings containing `\` that were fooling the as65 assembler. I took them out and the problem went away. I now have no workarounds - yay!

**Comment by Arakula** [comment]
No more workarounds? Cool!
