### ISSUE TITLE
a09 will not assemble 6502 code produced with dasmfw, can you recommend an alternative Windows assembler? 

### ISSUE THREAD

**Issue by phillipeaton** [Arakula/dasmfw#3]
Perhaps the assembler you used for 6502 testing? You did do some testing, right? 😀

Thanks!

**Comment by Arakula** [comment]
Unfortunately, still not an area of expertise for me ...

Can _you_ recommend one I might try on Windows or Linux, with download link, if possible?

**Comment by phillipeaton** [comment]
The last 6502 assembler I used was typed in from the back of a Melbourne House book in the mid-80s, so I'm no expert!

This week, I tried using as65 assembler from the assembler set here: [kingswood-consulting.co.uk](http://hg.kingswood-consulting.co.uk/assemblers/index.html), because the 6809 version is popular with Vectrex users over the past 25 years or so. However, they're proprietary and the "-i" switch bug has had no response from the author for a long time. 

A current popular assembler for the C64 that I'm currently looking at is [Kick Assembler ](http://www.theweb.dk/KickAssembler/Main.html#frontpage), maybe I'll migrate to this one after my inital tests, although it relies on Java, and I like things that are simple, so maybe I'll look elsewhere.

An alternative for me is the assembler inside the [CBM Prg Studio](http://www.ajordison.co.uk/index.html), but, like the Kick assembler, it's not exactly a general purpose assembler. (Plus, it's author is currently working on additionally, supporting Kick Assembler.)

![image](https://user-images.githubusercontent.com/44277038/166875954-5a0e99ef-2c2f-4ca6-9775-854c2f9c309d.png)

I'm not sure this is much help...

**Comment by Arakula** [comment]
Since I don't have any, it sure is :-)

**Comment by Arakula** [comment]
That Kick Assembler looks particularly interesting ... gives me really bad ideas ... like adding a Python interface to A09 :-)

**Comment by phillipeaton** [comment]
Or maybe you add 6502 capability to a09? (a02?)  Maybe I should hide now 😉

**Comment by Arakula** [comment]
I won't. That would require quite some changes, mostly "thanks" to the fact that the 650X is a little-endian processor. That doesn't fit well into the A09 code. A separate "A02" would be an option ... and if/when I run into a situation where I might need it, that will presumably happen (I like having both disassembly and assembly under my thumb, following my rules ;-) ).
