### ISSUE TITLE
Disassembling 6502 code is giving me "RTI A" instead of "RTI" for code $40, which appears invalid?

### ISSUE THREAD

**Issue by phillipeaton** [Arakula/dasmfw#5]
I'm a total newbie with 6502 code, but this appears wrong as far as I can tell? 

Thanks!

**Comment by Arakula** [comment]
You seem to be the first one ever using the 6502 disassembler :-)
That one's not exactly fully mature yet.
I'll look into it.

**Comment by phillipeaton** [comment]
I knew that when I started, you commented somewhere as such. The program gave me such good results for 6809, it's worth being a tester! (My 6809 project is still active, will publish results eventually.)

**Comment by Arakula** [comment]
Hmmm, looks like a table error ...
```
  _rti  ,_acc,   ...     /* 40..43 */
```
where it should rather be
```
  _rti  ,_imp,   ...     /* 40..43 */
```
in some places (one for each supported 65xx family member instruction set).
If you're feeling lucky, you might try that simple fix. Should occur in 3 lines in Dasm6500.cpp (lines 115, 1064, 1288 in my local copy).

**Comment by phillipeaton** [comment]
Thanks for the fix.

Last time you made available a patched binary, but this time I have VC2019 installed and have now been able successfully recompile dasmfw and the fix appears to work!

![image](https://user-images.githubusercontent.com/44277038/166877246-16e940a5-1c5f-4258-9629-52bc8fc63152.png)

I assume you'll put it into the next release.

**Comment by Arakula** [comment]
Yes, of course. I'll presumably upload a "Philip Eaton release" later today.
